name: dreamt
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - captum=0.7.0=0
  - cffi=1.16.0=py310h2fee648_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hd41b1e2_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.7=py310hc6cd4ac_0
  - dcor=0.6=pyhd8ed1ab_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - fdasrsf=2.5.6=py310hcc13569_5
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.3=pyhd8ed1ab_0
  - findiff=0.10.0=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.3.1=pyhca7485f_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - h5py=3.11.0=nompi_py310h65828d5_100
  - hdf5=1.14.3=nompi_h4f84152_100
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.25.1=hf27288f_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.6.0=ha9c0a0a_2
  - libtorch=2.1.2=cpu_generic_ha017de0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - matplotlib-base=3.8.2=py310h62c0568_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multimethod=1.9.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.58.1=py310h7dc5dd1_0
  - numpy=1.22.4=py310h4ef5377_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.3.1=h4ab18f5_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.5=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.40=pyha770c72_0
  - prompt_toolkit=3.0.40=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.1.2=cpu_generic_py310h5d8fa8e_3
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyzmq=25.1.1=py310h795f18f_2
  - rdata=0.10.0=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - scikit-datasets=0.2.4=pyhd8ed1ab_0
  - scikit-fda=0.9=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.1.2=py310_cu121
  - torchvision=0.16.2=py310_cu121
  - tornado=6.3.3=py310h2372a71_1
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xarray=2023.12.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - aeon==0.5.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - autograd==1.6.2
      - beautifulsoup4==4.12.3
      - bidict==0.23.1
      - biosppy==2.2.1
      - blis==0.7.11
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.0.0
      - confection==0.1.3
      - cramjam==2.8.3
      - cymem==2.0.8
      - deap==1.4.1
      - deprecated==1.2.13
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - fastai==2.7.13
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastjsonschema==2.19.0
      - fastparquet==2024.2.0
      - fastprogress==1.0.3
      - flatbuffers==24.3.25
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - future==0.18.3
      - gast==0.5.4
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gpboost==1.2.7.1
      - grpcio==1.64.0
      - heartpy==1.2.7
      - hmmlearn==0.3.0
      - hyperopt==0.2.7
      - idna==3.4
      - imbalanced-learn==0.12.3
      - ipywidgets==8.1.1
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyterlab-widgets==3.0.9
      - keras==2.14.0
      - langcodes==3.3.0
      - libclang==18.1.1
      - lightgbm==4.1.0
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - llvmlite==0.41.1
      - locket==1.0.0
      - mako==1.3.5
      - markdown==3.3.4
      - markupsafe==2.1.2
      - matplotlib==3.8.1
      - ml-dtypes==0.2.0
      - mne==1.5.1
      - mock==5.1.0
      - multidict==6.0.4
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - nbformat==5.9.2
      - neurokit2==0.2.7
      - oauthlib==3.2.2
      - onnx==1.16.2
      - opencv-python==4.6.0.66
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - partd==1.2.0
      - pathtools==0.1.2
      - pillow==9.3.0
      - platformdirs==3.11.0
      - plotly==5.18.0
      - pooch==1.8.0
      - preshed==3.0.9
      - protobuf==4.25.0
      - psutil==5.9.6
      - py4j==0.10.9.7
      - pyaml==24.4.0
      - pyarrow==15.0.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pyedflib==0.1.36
      - pymer4==0.8.1
      - pymop==0.2.4
      - pytorch-lightning==2.1.0
      - pyts==0.13.0
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - referencing==0.31.0
      - requests==2.28.1
      - requests-oauthlib==2.0.0
      - rpds-py==0.13.1
      - rpy2==3.5.15
      - rsa==4.9
      - scikit-base==0.6.1
      - scikit-learn==1.3.0
      - scikit-optimize==0.10.1
      - scipy==1.11.3
      - seaborn==0.13.0
      - sentry-sdk==1.34.0
      - setproctitle==1.3.3
      - shap==0.43.0
      - shortuuid==1.0.13
      - sktime==0.24.1
      - slicer==0.0.7
      - smart-open==6.4.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - statsmodels==0.14.1
      - stumpy==1.12.0
      - tenacity==8.2.3
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.1
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tf-explain==0.3.1
      - thinc==8.2.1
      - time-interpret==0.3.0
      - toolz==0.12.1
      - torchcam==0.4.0
      - torchmetrics==1.2.0
      - tqdm==4.65.2
      - tsai==0.3.8
      - tsflex==0.3.0
      - tsfresh==0.20.2
      - tsinterpret==0.4.5
      - tslearn==0.6.3
      - typer==0.9.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==1.26.13
      - wandb==0.15.12
      - wasabi==1.1.2
      - weasel==0.3.4
      - werkzeug==3.0.3
      - wfdb==4.1.2
      - widgetsnbextension==4.0.9
      - wrapt==1.14.1
      - xgboost==2.0.2
      - yarl==1.9.2
prefix: /home/kw302/miniconda3/envs/dreamt
